### ISSUE TITLE
[Bug]: Generated AppManifest doen't contain all VSS dataPoints

### ISSUE THREAD

**Issue by gkreyssing** [eclipse-velocitas/velocitas-project-generator-npm#25]
### Severity

High

### What release version, tag or commit-hash did you use?

2.2.0

### Current Behavior

The AppManifest doesn't make a explicit distinction between read and write access of data points.

### Steps to Reproduce

1. Open https://digitalauto.netlify.app/model/STLWzk1WyqVVLbfymb4f/library/prototype/wn6bU7ncCT5WSTfXu66m/view/code
2. Click on "Create Eclipse Velocitas Project", enter repository name and click on "Create Repository"
3. Open the created repository
4. Check the dataPoints in the /app/AppManifest.json 
            "datapoints": [
                {
                    "path": "Vehicle.Body.Hood.IsOpen",
                    "required": "true",
                    "access": "write"
                },
                {
                    "path": "Vehicle.Body.Windshield.Front.Wiping.Mode",
                    "required": "true",
                    "access": "write"
                }
            ]

### Expected Behavior

The app uses the following datapoints:
- await self.Vehicle.Body.Hood.IsOpen.set(False)
- await self.Vehicle.Body.Hood.IsOpen.subscribe(self.on_hood_is_open_changed)
- await self.Vehicle.Body.Windshield.Front.Wiping.Mode.set("MEDIUM")

but self.Vehicle.Body.Hood.IsOpen.subscribe is not reflected in the AppManifest.json

### Additional Information

From a pure Authorization Concept point of view Vehicle.Body.Hood.IsOpen (Write) covers Vehicle.Body.Hood.IsOpen (Read), but in my opinion, we have to make the distinction between write and read as we need this information to resolve the Kuksa VSS Provider (Data Provider or Actuation Provider) before the app gets deployed to the vehicle. 

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by doosuu** [comment]
For all datapoints we always use the highest possible access mode that is used in the source code. I.e. if a data point is read only via i.e. `Vehicle.Speed.get()` then the access mode is `read`, if there is a `Vehicle.Speed.get()` and a `Vehicle.Speed.set(100)` in the code, then the access mode is deducted as `write`. `subscribe` is just a continuous `read` access mode.

The other issue you are mentioning is a valid point. When this bug was raised, there was no way to declare in the AppManifest whether the app is actually just a consumer of a datapoint or whether it itself is the provider of a datapoint.

This has been solved by https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/185 where datapoints can be provided or required. In case of a digital auto export, it is assumed that all datapoints are required because we are only expecting apps and no services coming from digital auto.

@gkreyssing with this, can the issue be closed?
